-- =====================================================================
-- CyberShield - Batch 5 Feature Migration
-- Run this AFTER db_migration_batch1/2/3/4.sql.
-- Adds: ASSIGNED_AT timestamp (needed to compute investigator resolution
-- time), and a Complaint Feedback table so citizens can rate how their
-- case was handled once it's Resolved/Rejected.
-- =====================================================================

-- Needed to compute "average resolution time" per investigator
ALTER TABLE COMPLAINTS ADD ASSIGNED_AT TIMESTAMP(6);

-- Citizen's rating of how their specific case was handled (distinct from
-- the general site FEEDBACK table - this is tied to one complaint).
CREATE TABLE COMPLAINT_FEEDBACK (
    COMPLAINT_FEEDBACK_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    COMPLAINT_ID NUMBER NOT NULL,
    USER_ID       NUMBER NOT NULL,
    RATING        NUMBER(1) NOT NULL,
    COMMENTS      VARCHAR2(1000),
    CREATED_AT    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COMPLAINT_ID) REFERENCES COMPLAINTS(COMPLAINT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT UQ_COMPLAINT_FEEDBACK UNIQUE (COMPLAINT_ID)
);
