-- =====================================================================
-- CyberShield - Batch 2 Feature Migration
-- Run this AFTER db_migration_batch1.sql.
-- Adds: District field on complaints (for the District Safety Bulletin),
--       Community Verification / Trust Scoring (corroborations on
--       Suspect Repository entries).
-- Pre-emptive URL/QR Risk Check reuses the existing AI engine and
-- SUSPECTS/THREATS tables directly, so it needs no new tables.
-- =====================================================================

-- 1. District Safety Bulletin ------------------------------------------
ALTER TABLE COMPLAINTS ADD DISTRICT VARCHAR2(60);

-- 2. Community Verification / Trust Scoring -----------------------------
-- Lightweight "I got this too" corroboration against an existing SUSPECTS
-- entry - one per citizen per suspect (no duplicate corroboration).
CREATE TABLE SUSPECT_CORROBORATIONS (
    CORROBORATION_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SUSPECT_ID        NUMBER NOT NULL,
    USER_ID           NUMBER NOT NULL,
    CREATED_AT         TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SUSPECT_ID) REFERENCES SUSPECTS(SUSPECT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT UQ_SUSPECT_USER_CORROBORATION UNIQUE (SUSPECT_ID, USER_ID)
);
