-- =====================================================================
-- CyberShield - Batch 1 Feature Migration
-- Run this AFTER the base schema in PROJECT_DOCUMENTATION.md is created.
-- Adds: complaint category split, Feedback, Suspect Repository &
--       Report Suspect (with personal report history), Learning Corner
--       (Learning Corner content is static JSP + reuses existing tables,
--        so no new tables are needed for it).
-- =====================================================================

-- 1. Complaint category restructure -----------------------------------
-- COMPLAINT_TYPE will now hold one of exactly 3 top-level categories:
--   'Women & Child Related Crime', 'Financial Fraud', 'Other Cybercrime'
-- SUB_TYPE holds the specific incident type chosen under that category.
ALTER TABLE COMPLAINTS ADD SUB_TYPE VARCHAR2(150);

-- 2. Feedback ----------------------------------------------------------
CREATE TABLE FEEDBACK (
    FEEDBACK_ID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID       NUMBER,
    NAME          VARCHAR2(150),
    EMAIL         VARCHAR2(200),
    CATEGORY      VARCHAR2(60) NOT NULL,
    RATING        NUMBER(1) NOT NULL,
    MESSAGE       VARCHAR2(2000) NOT NULL,
    CREATED_AT    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 3. Suspect Repository (Check Suspect + Report Suspect) ---------------
-- Master registry of reported identifiers (email / mobile / URL / social handle)
CREATE TABLE SUSPECTS (
    SUSPECT_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IDENTIFIER_TYPE  VARCHAR2(30) NOT NULL,   -- EMAIL, MOBILE, URL, SOCIAL_HANDLE
    IDENTIFIER_VALUE VARCHAR2(300) NOT NULL,
    PLATFORM         VARCHAR2(100),
    REPORT_COUNT     NUMBER DEFAULT 1,
    STATUS           VARCHAR2(30) DEFAULT 'ACTIVE',
    CREATED_AT       TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

-- Individual "Report Suspect" submissions (also powers "My Reported Suspects")
CREATE TABLE SUSPECT_REPORTS (
    SUSPECT_REPORT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SUSPECT_ID        NUMBER NOT NULL,
    USER_ID           NUMBER NOT NULL,
    REPORT_CATEGORY   VARCHAR2(60) NOT NULL,  -- e.g. Social Media Abuse, Scam Call, Fake Profile, Other
    PLATFORM          VARCHAR2(100),
    DETAILS           VARCHAR2(2000),
    EVIDENCE_PATH     VARCHAR2(1000),
    CREATED_AT        TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SUSPECT_ID) REFERENCES SUSPECTS(SUSPECT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE INDEX IDX_SUSPECTS_IDVALUE ON SUSPECTS(IDENTIFIER_VALUE);
